const crypto = require('crypto');
const prisma = require('../../config/db');
const { getConfig } = require('../../utils/configHelper');

const getFrontendUrl = async () => {
    return (await getConfig('frontend_url')) || process.env.FRONTEND_URL || 'http://localhost:9002';
};

const generateInviteKey = () => crypto.randomBytes(12).toString('hex');

exports.createNFCCardIssuance = async (req, res) => {
    try {
        const { orderId } = req.params;
        const {
            nfcCardNumber,
            method = 'taptoinvite_site',
            calendarUrl,
            locationUrl,
            digitalInvitationType,
            digitalInvitationContent,
            websiteUrl,
            googleCalendarLink,
            status = 'registered',
        } = req.body;

        if (!orderId || !nfcCardNumber) {
            return res.status(400).json({ success: false, message: 'Order ID and NFC card number are required.' });
        }

        const order = await prisma.order.findUnique({
            where: { id: parseInt(orderId) },
            select: { id: true, order_number: true }
        });

        if (!order) {
            return res.status(404).json({ success: false, message: 'Order not found.' });
        }

        const frontendUrl = await getFrontendUrl();
        const autogeneratedKey = generateInviteKey();
        const generatedUrl = `${frontendUrl}/invite/${autogeneratedKey}`;

        const issuance = await prisma.nFCCardIssuance.create({
            data: {
                order_id: order.id,
                nfc_card_number: String(nfcCardNumber).trim(),
                autogenerated_key: autogeneratedKey,
                generated_url: generatedUrl,
                method: String(method),
                calendar_url: calendarUrl || null,
                location_url: locationUrl || null,
                digital_invitation_type: digitalInvitationType || null,
                digital_invitation_content: digitalInvitationContent || null,
                website_url: websiteUrl || null,
                google_calendar_link: googleCalendarLink || null,
                status: String(status),
            },
        });

        res.status(201).json({
            success: true,
            message: 'Card registered successfully',
            data: {
                id: issuance.id,
                orderId: order.id,
                orderNumber: order.order_number,
                nfcCardNumber: issuance.nfc_card_number,
                autogeneratedKey: issuance.autogenerated_key,
                generatedUrl: issuance.generated_url,
                method: issuance.method,
                status: issuance.status,
            },
        });
    } catch (error) {
        console.error('Create NFC Issuance Error:', error);
        res.status(500).json({ success: false, message: 'Failed to register NFC card', error: error.message });
    }
};

exports.getOrderNFCCardIssuances = async (req, res) => {
    try {
        const { orderId } = req.params;

        const issuances = await prisma.nFCCardIssuance.findMany({
            where: { order_id: parseInt(orderId) },
            orderBy: { created_at: 'desc' },
        });

        res.status(200).json({ success: true, data: issuances });
    } catch (error) {
        console.error('Get NFC Issuances Error:', error);
        res.status(500).json({ success: false, message: 'Failed to fetch NFC issuances', error: error.message });
    }
};

exports.createOrderTrackingNote = async (req, res) => {
    try {
        const { orderId } = req.params;
        const { noteDate, noteTime, heading, description, visibleToUser = true } = req.body;

        if (!orderId || !noteDate || !noteTime || !heading || !description) {
            return res.status(400).json({
                success: false,
                message: 'Order ID, note date, note time, heading, and description are required.',
            });
        }

        const order = await prisma.order.findUnique({
            where: { id: parseInt(orderId) },
            select: { id: true, order_number: true }
        });

        if (!order) {
            return res.status(404).json({ success: false, message: 'Order not found.' });
        }

        const note = await prisma.orderTrackingNote.create({
            data: {
                order_id: order.id,
                note_date: new Date(noteDate),
                note_time: String(noteTime),
                heading: String(heading).trim(),
                description: String(description).trim(),
                visible_to_user: Boolean(visibleToUser),
            },
        });

        res.status(201).json({
            success: true,
            message: 'Tracking note saved successfully',
            data: {
                id: note.id,
                orderId: order.id,
                orderNumber: order.order_number,
                noteDate: note.note_date,
                noteTime: note.note_time,
                heading: note.heading,
                description: note.description,
                visibleToUser: note.visible_to_user,
            },
        });
    } catch (error) {
        console.error('Create Tracking Note Error:', error);
        res.status(500).json({ success: false, message: 'Failed to save tracking note', error: error.message });
    }
};

exports.getOrderTrackingNotes = async (req, res) => {
    try {
        const { orderId } = req.params;

        const notes = await prisma.orderTrackingNote.findMany({
            where: { order_id: parseInt(orderId) },
            orderBy: { created_at: 'desc' },
        });

        res.status(200).json({ success: true, data: notes });
    } catch (error) {
        console.error('Get Tracking Notes Error:', error);
        res.status(500).json({ success: false, message: 'Failed to fetch tracking notes', error: error.message });
    }
};

exports.getAllOrders = async (req, res) => {
    try {
        const orders = await prisma.order.findMany({
            include: {
                user: { select: { name: true, email: true } },
                plan: { select: { name: true } },
                category: { select: { name: true } },
                tracking_notes: { orderBy: { created_at: 'desc' }, take: 1 }
            },
            orderBy: { created_at: 'desc' }
        });
        res.status(200).json({ success: true, data: orders });
    } catch (error) {
        console.error('Get All Orders Error:', error);
        res.status(500).json({ success: false, message: 'Failed to fetch orders', error: error.message });
    }
};

exports.getRecentTrackingNotes = async (req, res) => {
    try {
        const notes = await prisma.orderTrackingNote.findMany({
            include: { order: { select: { order_number: true } } },
            orderBy: { created_at: 'desc' },
            take: 10
        });
        res.status(200).json({ success: true, data: notes });
    } catch (error) {
        console.error('Get Recent Tracking Notes Error:', error);
        res.status(500).json({ success: false, message: 'Failed to fetch tracking notes', error: error.message });
    }
};
