const crypto = require('crypto');
const prisma = require('../../config/db');
const { getConfig } = require('../../utils/configHelper');

const getFrontendUrl = async () => {
    return (await getConfig('frontend_url')) || process.env.FRONTEND_URL || 'http://localhost:9002';
};

const generateInviteKey = () => crypto.randomBytes(12).toString('hex');

exports.createNFCCardIssuance = async (req, res) => {
    try {
        const { orderId } = req.params;
        const {
            nfcCardNumber,
            method = 'taptoinvite_site',
            calendarUrl,
            locationUrl,
            digitalInvitationType,
            digitalInvitationContent,
            websiteUrl,
            googleCalendarLink,
            status = 'registered',
        } = req.body;

        if (!orderId || !nfcCardNumber) {
            return res.status(400).json({ success: false, message: 'Order ID and NFC card number are required.' });
        }

        const order = await prisma.order.findUnique({
            where: { id: parseInt(orderId) },
            select: { id: true, order_number: true }
        });

        if (!order) {
            return res.status(404).json({ success: false, message: 'Order not found.' });
        }

        const frontendUrl = await getFrontendUrl();
        const autogeneratedKey = generateInviteKey();
        const generatedUrl = `${frontendUrl}/invite/${autogeneratedKey}`;

        const issuance = await prisma.nFCCardIssuance.create({
            data: {
                order_id: order.id,
                nfc_card_number: String(nfcCardNumber).trim(),
                autogenerated_key: autogeneratedKey,
                generated_url: generatedUrl,
                method: String(method),
                calendar_url: calendarUrl || null,
                location_url: locationUrl || null,
                digital_invitation_type: digitalInvitationType || null,
                digital_invitation_content: digitalInvitationContent || null,
                website_url: websiteUrl || null,
                google_calendar_link: googleCalendarLink || null,
                status: String(status),
            },
        });

        res.status(201).json({
            success: true,
            message: 'Card registered successfully',
            data: {
                id: issuance.id,
                orderId: order.id,
                orderNumber: order.order_number,
                nfcCardNumber: issuance.nfc_card_number,
                autogeneratedKey: issuance.autogenerated_key,
                generatedUrl: issuance.generated_url,
                method: issuance.method,
                status: issuance.status,
            },
        });
    } catch (error) {
        console.error('Create NFC Issuance Error:', error);
        res.status(500).json({ success: false, message: 'Failed to register NFC card', error: error.message });
    }
};

exports.getOrderNFCCardIssuances = async (req, res) => {
    try {
        const { orderId } = req.params;

        const issuances = await prisma.nFCCardIssuance.findMany({
            where: { order_id: parseInt(orderId) },
            orderBy: { created_at: 'desc' },
        });

        res.status(200).json({ success: true, data: issuances });
    } catch (error) {
        console.error('Get NFC Issuances Error:', error);
        res.status(500).json({ success: false, message: 'Failed to fetch NFC issuances', error: error.message });
    }
};

exports.createOrderTrackingNote = async (req, res) => {
    try {
        const { orderId } = req.params;
        const { noteDate, noteTime, heading, description, visibleToUser = true } = req.body;

        if (!orderId || !noteDate || !noteTime || !heading || !description) {
            return res.status(400).json({
                success: false,
                message: 'Order ID, note date, note time, heading, and description are required.',
            });
        }

        const order = await prisma.order.findUnique({
            where: { id: parseInt(orderId) },
            select: { id: true, order_number: true }
        });

        if (!order) {
            return res.status(404).json({ success: false, message: 'Order not found.' });
        }

        const note = await prisma.orderTrackingNote.create({
            data: {
                order_id: order.id,
                note_date: new Date(noteDate),
                note_time: String(noteTime),
                heading: String(heading).trim(),
                description: String(description).trim(),
                visible_to_user: Boolean(visibleToUser),
            },
        });

        res.status(201).json({
            success: true,
            message: 'Tracking note saved successfully',
            data: {
                id: note.id,
                orderId: order.id,
                orderNumber: order.order_number,
                noteDate: note.note_date,
                noteTime: note.note_time,
                heading: note.heading,
                description: note.description,
                visibleToUser: note.visible_to_user,
            },
        });
    } catch (error) {
        console.error('Create Tracking Note Error:', error);
        res.status(500).json({ success: false, message: 'Failed to save tracking note', error: error.message });
    }
};

exports.getOrderTrackingNotes = async (req, res) => {
    try {
        const { orderId } = req.params;

        const notes = await prisma.orderTrackingNote.findMany({
            where: { order_id: parseInt(orderId) },
            orderBy: { created_at: 'desc' },
        });

        res.status(200).json({ success: true, data: notes });
    } catch (error) {
        console.error('Get Tracking Notes Error:', error);
        res.status(500).json({ success: false, message: 'Failed to fetch tracking notes', error: error.message });
    }
};

exports.getAllOrders = async (req, res) => {
    try {
        const orders = await prisma.order.findMany({
            include: {
                user: { select: { id: true, name: true, email: true, phone: true } },
                plan: { select: { id: true, name: true } },
                category: { select: { id: true, name: true } },
                tracking_notes: { orderBy: { created_at: 'desc' }, take: 1 },
                payments: { select: { amount: true, status: true } },
                _count: { select: { payments: true, items: true } }
            },
            orderBy: { created_at: 'desc' }
        });

        // Add total_paid calculation
        const normalized = orders.map(o => ({
            ...o,
            total_paid: o.payments
                .filter(p => p.status !== 'Refunded')
                .reduce((sum, p) => sum + parseFloat(p.amount), 0),
            payments: undefined // remove raw payments array
        }));

        res.status(200).json({ success: true, data: normalized });
    } catch (error) {
        console.error('Get All Orders Error:', error);
        res.status(500).json({ success: false, message: 'Failed to fetch orders', error: error.message });
    }
};

// ─── GET ORDER DETAIL ────────────────────────────────────────────────────────
exports.getOrderById = async (req, res) => {
    try {
        const { id } = req.params;

        const order = await prisma.order.findUnique({
            where: { id: parseInt(id) },
            include: {
                user: { select: { id: true, name: true, email: true, phone: true, country_code: true } },
                plan: { select: { id: true, name: true, base_price: true } },
                category: { select: { id: true, name: true } },
                items: true,
                tracking_notes: { orderBy: { created_at: 'desc' } },
                nfc_issuances: { orderBy: { created_at: 'desc' } },
                payments: {
                    orderBy: { transaction_date: 'desc' },
                    include: { marked_by: { select: { id: true, name: true } } }
                }
            }
        });

        if (!order) return res.status(404).json({ success: false, message: 'Order not found.' });

        // Calculate total paid
        const total_paid = order.payments
            .filter(p => p.status !== 'Refunded')
            .reduce((sum, p) => sum + parseFloat(p.amount), 0);

        res.status(200).json({
            success: true,
            data: { ...order, total_paid }
        });
    } catch (error) {
        console.error('Get Order Detail Error:', error);
        res.status(500).json({ success: false, message: 'Failed to fetch order', error: error.message });
    }
};

// ─── UPDATE ORDER STATUS ─────────────────────────────────────────────────────
exports.updateOrderStatus = async (req, res) => {
    try {
        const { id } = req.params;
        const { order_status, payment_status } = req.body;

        const updateData = {};
        if (order_status) updateData.order_status = order_status;
        if (payment_status) updateData.payment_status = payment_status;

        if (Object.keys(updateData).length === 0) {
            return res.status(400).json({ success: false, message: 'Provide order_status or payment_status.' });
        }

        await prisma.order.update({
            where: { id: parseInt(id) },
            data: updateData
        });

        res.status(200).json({ success: true, message: 'Order updated successfully.' });
    } catch (error) {
        console.error('Update Order Status Error:', error);
        res.status(500).json({ success: false, message: 'Failed to update order', error: error.message });
    }
};

// ─── RECORD PAYMENT ──────────────────────────────────────────────────────────
exports.recordPayment = async (req, res) => {
    try {
        const { order_id, transaction_id, amount, payment_note, status, mode, transaction_date } = req.body;
        const markedById = req.user.id;

        if (!order_id || !amount || !transaction_date) {
            return res.status(400).json({ success: false, message: 'order_id, amount, and transaction_date are required.' });
        }

        const order = await prisma.order.findUnique({ where: { id: parseInt(order_id) } });
        if (!order) return res.status(404).json({ success: false, message: 'Order not found.' });

        const payment = await prisma.payment.create({
            data: {
                order_id: parseInt(order_id),
                transaction_id: transaction_id || null,
                amount: parseFloat(amount),
                payment_note: payment_note || null,
                status: status || 'Advance_Paid',
                mode: mode || 'online',
                transaction_date: new Date(transaction_date),
                marked_by_id: markedById
            },
            include: {
                marked_by: { select: { id: true, name: true } }
            }
        });

        // Auto-update order payment_status based on total paid
        const allPayments = await prisma.payment.findMany({
            where: { order_id: parseInt(order_id), status: { not: 'Refunded' } }
        });
        const totalPaid = allPayments.reduce((sum, p) => sum + parseFloat(p.amount), 0);
        const orderTotal = parseFloat(order.total_amount);

        let newPaymentStatus = 'Pending';
        if (totalPaid >= orderTotal) newPaymentStatus = 'Fully_Paid';
        else if (totalPaid > 0) newPaymentStatus = 'Advance_Paid';

        await prisma.order.update({
            where: { id: parseInt(order_id) },
            data: { payment_status: newPaymentStatus }
        });

        res.status(201).json({
            success: true,
            message: 'Payment recorded successfully.',
            data: { ...payment, updated_order_payment_status: newPaymentStatus }
        });
    } catch (error) {
        console.error('Record Payment Error:', error);
        res.status(500).json({ success: false, message: 'Failed to record payment', error: error.message });
    }
};

// ─── GET ORDER PAYMENTS ──────────────────────────────────────────────────────
exports.getOrderPayments = async (req, res) => {
    try {
        const { orderId } = req.params;

        const payments = await prisma.payment.findMany({
            where: { order_id: parseInt(orderId) },
            orderBy: { transaction_date: 'desc' },
            include: {
                marked_by: { select: { id: true, name: true } }
            }
        });

        res.status(200).json({ success: true, data: payments });
    } catch (error) {
        console.error('Get Payments Error:', error);
        res.status(500).json({ success: false, message: 'Failed to fetch payments', error: error.message });
    }
};

exports.getRecentTrackingNotes = async (req, res) => {
    try {
        const notes = await prisma.orderTrackingNote.findMany({
            include: { order: { select: { order_number: true } } },
            orderBy: { created_at: 'desc' },
            take: 10
        });
        res.status(200).json({ success: true, data: notes });
    } catch (error) {
        console.error('Get Recent Tracking Notes Error:', error);
        res.status(500).json({ success: false, message: 'Failed to fetch tracking notes', error: error.message });
    }
};
