-- CreateTable
CREATE TABLE `NFCCardIssuance` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `order_id` INTEGER NOT NULL,
    `nfc_card_number` VARCHAR(191) NOT NULL,
    `autogenerated_key` VARCHAR(191) NOT NULL,
    `generated_url` VARCHAR(191) NOT NULL,
    `method` VARCHAR(191) NOT NULL DEFAULT 'taptoinvite_site',
    `calendar_url` LONGTEXT NULL,
    `location_url` LONGTEXT NULL,
    `digital_invitation_type` VARCHAR(191) NULL,
    `digital_invitation_content` LONGTEXT NULL,
    `website_url` LONGTEXT NULL,
    `google_calendar_link` LONGTEXT NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'registered',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    `encoded_at` DATETIME(3) NULL,
    `shipped_at` DATETIME(3) NULL,

    UNIQUE INDEX `NFCCardIssuance_nfc_card_number_key`(`nfc_card_number`),
    UNIQUE INDEX `NFCCardIssuance_autogenerated_key_key`(`autogenerated_key`),
    UNIQUE INDEX `NFCCardIssuance_generated_url_key`(`generated_url`),
    INDEX `NFCCardIssuance_order_id_idx`(`order_id`),
    INDEX `NFCCardIssuance_autogenerated_key_idx`(`autogenerated_key`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OrderTrackingNote` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `order_id` INTEGER NOT NULL,
    `note_date` DATETIME(3) NOT NULL,
    `note_time` VARCHAR(191) NOT NULL,
    `heading` VARCHAR(191) NOT NULL,
    `description` LONGTEXT NOT NULL,
    `visible_to_user` BOOLEAN NOT NULL DEFAULT true,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `OrderTrackingNote_order_id_idx`(`order_id`),
    INDEX `OrderTrackingNote_visible_to_user_idx`(`visible_to_user`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `NFCCardIssuance` ADD CONSTRAINT `NFCCardIssuance_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `Order`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `OrderTrackingNote` ADD CONSTRAINT `OrderTrackingNote_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `Order`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
